"""Prometheus /metrics for TabbyAPI, added without rebuilding the pinned image.

Mounted into the container and put on PYTHONPATH by start-tabbyapi.sh, so Python
imports it at startup. It wraps two TabbyAPI functions as their modules load:

  common.gen_logging.log_metrics  adds each finished request's gen_tokens and
                                  gen_time to running totals
  endpoints.server.setup_app      adds GET /metrics to the FastAPI app it builds

Only those totals are kept: no prompts, outputs, request ids or timings per request.
The route sits behind TabbyAPI's usual global dependencies and the loopback-only port
the launcher publishes. If a hook can't be applied, TabbyAPI starts unchanged.

Written against TabbyAPI f07131cd8fe34e449fe87cdd3a066b52b96d3cac.
"""
import importlib.abc
import math
import sys
import threading

_lock = threading.Lock()
_totals = {'tokens': 0, 'seconds': 0.0, 'requests': 0}


def record(metrics):
    """Add one finished request's generation counts. Ignores anything malformed."""
    try:
        tokens = int(metrics.get('gen_tokens') or 0)
        seconds = float(metrics.get('gen_time') or 0.0)
    except (AttributeError, TypeError, ValueError):
        return
    if tokens < 0 or not math.isfinite(seconds) or seconds < 0:
        return
    with _lock:
        _totals['tokens'] += tokens
        _totals['seconds'] += seconds
        _totals['requests'] += 1


def render():
    with _lock:
        tokens, seconds, requests = _totals['tokens'], _totals['seconds'], _totals['requests']
    return (
        '# HELP tabbyapi_generated_tokens_total Tokens generated by finished requests.\n'
        '# TYPE tabbyapi_generated_tokens_total counter\n'
        f'tabbyapi_generated_tokens_total {tokens}\n'
        '# HELP tabbyapi_generation_seconds_total Seconds spent generating those tokens.\n'
        '# TYPE tabbyapi_generation_seconds_total counter\n'
        f'tabbyapi_generation_seconds_total {seconds:.6f}\n'
        '# HELP tabbyapi_requests_total Finished generation requests.\n'
        '# TYPE tabbyapi_requests_total counter\n'
        f'tabbyapi_requests_total {requests}\n'
    )


def _patch_gen_logging(module):
    original = module.log_metrics

    def log_metrics(label, metrics, *args, **kwargs):
        record(metrics)
        return original(label, metrics, *args, **kwargs)

    module.log_metrics = log_metrics


def _patch_server(module):
    original = module.setup_app

    def setup_app(*args, **kwargs):
        app = original(*args, **kwargs)
        from fastapi.responses import PlainTextResponse

        async def metrics():
            return PlainTextResponse(render(), media_type='text/plain; version=0.0.4')

        app.add_api_route('/metrics', metrics, methods=['GET'], include_in_schema=False)
        return app

    module.setup_app = setup_app


PATCHES = {'common.gen_logging': _patch_gen_logging, 'endpoints.server': _patch_server}


class _PatchingLoader(importlib.abc.Loader):
    def __init__(self, loader, patch):
        self._loader, self._patch = loader, patch

    def create_module(self, spec):
        return self._loader.create_module(spec)

    def exec_module(self, module):
        self._loader.exec_module(module)
        # Before the import returns, so `from common.gen_logging import log_metrics`
        # elsewhere already binds the wrapped function.
        try:
            self._patch(module)
        except Exception as error:  # never stop TabbyAPI over metrics
            print(f'tabby-metrics: {module.__name__} not patched ({type(error).__name__})', file=sys.stderr)


class _PatchingFinder(importlib.abc.MetaPathFinder):
    def find_spec(self, name, path, target=None):
        if name not in PATCHES:
            return None
        for finder in sys.meta_path:
            if finder is self or not hasattr(finder, 'find_spec'):
                continue
            spec = finder.find_spec(name, path, target)
            if spec is not None and spec.loader is not None:
                spec.loader = _PatchingLoader(spec.loader, PATCHES[name])
                return spec
        return None


if not any(isinstance(f, _PatchingFinder) for f in sys.meta_path):
    sys.meta_path.insert(0, _PatchingFinder())
